name: npm Build and Publish

on: [push]

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        uses: ./.github/actions/build

      - name: Update GQL Workspace Dependencies
        if: github.ref == 'refs/heads/main'
        working-directory: packages/gql
        run: |
          # Replace the build section with the published image
          sed -i '/    build:/,/      dockerfile:.*/ c\    image: ghcr.io/primodiumxyz/sdi-hasura-cache:main' docker-compose.yaml
      - name: Release GQL Package
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: packages/gql
        run: npx --package semantic-release --package semantic-release-monorepo semantic-release --branches main

      - name: Update Indexer Workspace Dependencies
        if: github.ref == 'refs/heads/main'
        working-directory: packages/indexer
        run: |
          # Get the latest published version of the GQL package
          LATEST_GQL_VERSION=$(npm view @primodiumxyz/dex-graphql version)
          # Update the dependency in package.json
          npm pkg set dependencies.@primodiumxyz/dex-graphql="^${LATEST_GQL_VERSION}"

      - name: Release Indexer Package
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: packages/indexer
        run: npx --package semantic-release --package semantic-release-monorepo semantic-release --branches main
